version: '3'
services:
  postgres:
    image: postgres:14.4-bullseye
    ports:
      - 6000:5432
    environment:
      - POSTGRES_DB=crowd
      - POSTGRES_USER=crowd
      - POSTGRES_PASSWORD=crowd
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

